name: openapi-generator-cli

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - "code-gen/openapi-generator-cli.jar"

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: generate
        run: |
          sh ./.github/actions/openapi-generator-cli/entrypoint.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}